name:  Deploy to environment

on: 
   workflow_dispatch:
     inputs:
       environment:
         type: string
         required: true
jobs:      
  deploy:
    runs-on: ubuntu-latest
    env: 
        
        environment: "${{ github.event.inputs.environment }}"
    steps:
    - name: Debug Variables
      env:
        MULE_HOST_NAME: "${{ vars.MULE_HOST_NAME }}"
      run: |
        echo "Environment: $environment"
        echo "MULE_HOST_NAME: $MULE_HOST_NAME"
    - name: Run Deployment command

      run: |
        if [[ "$environment" == "PROD" || "$environment" == "R1C2NFT" ]]; then
           echo "this is Prod "
        elif [[ "$environment" == "R1C3DEV" && "$MULE_HOST_NAME" == "a" ]]; then
           echo "this is a "
        elif [[ "$environment" == "R1C3DEV" && "$MULE_HOST_NAME" == "b" ]]; then
           echo "this is b "
        fi
      
       
      
         
