name: shell script Workflow

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4
          
        - name: Creating file
          run: touch manish.txt
        
        - name: permission
          run: chmod +rwx a.sh

        - name: execution of ascii
          run: ./a.sh
    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
        - name: file existence
          run: grep -i "manish " >> manish.txt

    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:
        - name: creation of directory
          run: echo "I am build jobs"