name: shell script Workflow

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4
          
        - name: Creating file
          run: sudo touch /tmp/manish.txt
        
        - name: permission
          run: chmod +rwx a.sh

        - name: execution of ascii
          run: ./a.sh
        - name: upload Artifacts
          uses: actions/upload-artifact@v4
          with:
           name: manish_artifacts
           path: /tmp/manish.txt 
    test_job: 
        needs: build_job
        runs-on: ubuntu-latest
        steps:
        
        - name: download Artifacts
          uses: actions/download-artifact@v4
          with:
           name: manish_artifacts

        - name: listing
          run: ls -l 
        - name: cat
          run: sudo cat manish.txt   
        - name: file existence
          run: sudo grep  "Manish" manish.txt

    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:
        - name: creation of directory
          run: echo "I am build jobs"